module.exports = [

            {id: 1,
            ingredientName: 'pepperoni',
            unit: 'ounces',
            amount: 8,
            recipe_id: 1},
            {id: 2,
            ingredientName: 'mozzerella chese',
            unit: 'ounces',
            amount: 10,
            recipe_id: 1},
            {id: 3,
            ingredientName: 'dough',
            unit: 'ounces',
            amount: 2,
            recipe_id: 1},
            {id: 4,
            ingredientName: 'marinara sauce',
            unit: 'ounces',
            amount: 16,
            recipe_id: 1},
            {id: 5,
            ingredientName: 'olive oil',
            unit: 'cup',
            amount: 2,
            recipe_id: 1},

];
